name: instagram_clone
description: A new Flutter project.

publish_to: 'none'


version: 1.0.0+1

environment:
  sdk: '>=3.1.0 <4.0.0'


dependencies:
  flutter:
    sdk: flutter



  cupertino_icons: ^1.0.2
  firebase_core: ^2.15.1
  cloud_firestore: ^4.9.1
  firebase_auth: ^4.9.0
  firebase_storage: ^11.2.6
  flutter_svg: ^2.0.7
  image_picker: ^1.0.4
  provider: ^6.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.1




flutter:


  uses-material-design: true


  assets:
    - assets/


  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
